name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST https://api.vercel.com/v13/deployments \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "ahmed-cars",
              "projectId": "prj_LYulXVxUmf3AptOGjLIM0fM8TrRJ",
              "gitSource": {
                "type": "github",
                "repo": "'"$GITHUB_REPOSITORY"'",
                "ref": "'"$GITHUB_REF"'"
              },
              "target": "production"
            }' 